export const menu = [
  {
    number: 1,
    name: "Margerita",
    ingredients: ["Ser mozarella", "Sos pomidorowy", "Bazylia"],
    price: { "35cm": 20, "45cm": 25 },
  },
  {
    number: 2,
    name: "Hawaii",
    ingredients: ["Ser mozarella", "Sos pomidorowy", "Ananas", "Szynka"],
    price: { "35cm": 23, "45cm": 28 },
  },
  {
    number: 3,
    name: "Prosciutto Fungi",
    ingredients: ["Ser mozarella", "Sos pomidorowy", "Pieczarki", "Szynka"],
    price: { "35cm": 23, "45cm": 28 },
  },
  {
    number: 4,
    name: "Vegetariana",
    ingredients: [
      "Brokuły",
      "Sos pomidorowy",
      "Pieczarki",
      "Pomidory Koktajlowe",
      "Rukola",
    ],
    price: { "35cm": 22, "45cm": 26 },
  },
  {
    number: 5,
    name: "Siciliana",
    ingredients: [
      "Cebula",
      "Sos pomidorowy",
      "Kapary",
      "Pomidory Koktajlowe",
      "Tuńczyk",
    ],
    price: { "35cm": 28, "45cm": 32 },
  },
];

export const additives = [
  { number: 0, name: "ananas", price: 3 },
  { number: 1, name: "bekon", price: 3 },
  { number: 2, name: "brokuły", price: 3 },
  { number: 3, name: "cebula", price: 3 },
  { number: 4, name: "czarne oliwki", price: 3 },
  { number: 5, name: "gruszka", price: 3 },
  { number: 6, name: "kapary", price: 3 },
  { number: 7, name: "karczochy", price: 3 },
  { number: 8, name: "kukurydza", price: 3 },
  { number: 9, name: "papryczki dżelapino", price: 3 },
  { number: 10, name: "papryka", price: 3 },
  { number: 11, name: "pieczarki", price: 3 },
  { number: 12, name: "pomidory koktajlowe", price: 3 },
  { number: 13, name: "pomidory suszone", price: 3 },
  { number: 14, name: "rukola", price: 3 },
  { number: 15, name: "salami chorizo", price: 3 },
  { number: 16, name: "salami klasyczne", price: 3 },
  { number: 17, name: "salami spinata", price: 3 },
  { number: 18, name: "ser biała mozarella", price: 3 },
  { number: 19, name: "ser gorgonzola", price: 3 },
  { number: 20, name: "ser lazur", price: 3 },
  { number: 21, name: "ser parmezan", price: 3 },
  { number: 22, name: "sos balsamico", price: 3 },
  { number: 23, name: "sos tabasco", price: 3 },
  { number: 24, name: "szynka", price: 3 },
  { number: 25, name: "szynka parmeńska", price: 3 },
  { number: 26, name: "tuńczyk", price: 3 },
  { number: 27, name: "wędzony kurczak", price: 3 },
  { number: 28, name: "ser feta", price: 3 },
  { number: 29, name: "szpinak", price: 3 },
];
